# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true
fabric.loom.disableMinecraftVerification=true

# Mod Properties
version = 3.2.3
maven_group = farn.nomaven
archives_base_name = ReiMinimap-Ornithe

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = b1.7.3
loader_version = 0.19.5
accesswidener_name=reiminimap

client_raven_build = 2
server_raven_build = 2
client_sparrow_build = 2
server_sparrow_build = 2
client_nests_build = 3
server_nests_build = 3
feather_build = 1
biny_mappings = bdae1bc
